import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillTwitterCircle,
} from "react-icons/ai";
import Tushar from "../public/Tushar.png";
import Code from "../public/code.png";
import Consulting from "../public/consulting.png";
import Design from "../public/design.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";
export default function Home() {
  const [darkMode, setdarkmode] = useState(true);
  return (
    <div className={darkMode ? " " : "dark"}>
      <Head>
        <title>Simple portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 bg-white md:px-20 lg:px-40 dark:bg-gray-900 ">
        <section className="min-h-screen dark:text-gray-200">
          <nav className="py-10 mb-12 flex items-center justify-between">
            <p className="text-xl dark:text-gray-300 cursor-pointer">
              Trust AFK
            </p>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setdarkmode(!darkMode)}
                  className=" text-lg cursor-pointer dark:text-yellow-300"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white rounded-md px-4 py-2 ml-8"
                  href="https://www.instagram.com/trust_afk/"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-3xl py-2 font-medium text-teal-500 md:text-5xl lg:text-6xl">
              Tushar Gupta
            </h2>
            <h3 className="text-xl py-2 md:text-3xl lg:text-4xl">Web Developer and <span>Designer</span> </h3>
            <p className="text-md text-gray-500 dark:text-gray-200 py-2 leading-8">
              Holla! a full time coder and an upcomming Engineer this side . Connect and explore with me!
            </p>
          </div>
          <div className="flex justify-center gap-16 text-5xl text-gray-500 pt-5 dark:text-gray-300">
            <a href="https://github.com/Tushar-gupta-git">
              <AiFillGithub className=" cursor-pointer" />
            </a>
            <a href="https://www.linkedin.com/in/tushar-gupta-10a151202/">
              <AiFillLinkedin className=" cursor-pointer" />
            </a>
            <a href="https://twitter.com/ohh_hii_tusharr">
              <AiFillTwitterCircle className=" cursor-pointer" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-90 h-90 bg-red-400">
            <Image layout="fill" objectFit="cover" src={Tushar} />
          </div>
        </section>
<br />
        <section className=" mt-5 dark:text-gray-200">
          <div>
            <h2 className="text-4xl font-medium py-3 dark:text-gray-200">
              Services I Offer
            </h2>
            <p className="text-md font-medium text-gray-800 py-1 leading-7 dark:text-gray-200">
              Since the begning of my jounreny as a freelancer designer and
              developer, i have done remote work for{" "}
              <span className="text-teal-500">agencies</span> consulted for{" "}
              <span className="text-teal-500">startups</span> and collaborated
              with talented people to create digital products for both bussiness
              and consumer use.
            </p>
            <p className="text-md font-medium text-gray-800 leading-7 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>

          <div className="md:flex gap-4 lg:flex gap-10">
            <div className="shadow-lg p-10 rounded-xl text-center my-10 border-slate-400 dark:shadow-cyan-500/50   ">
              <Image src={Design} width={100} height={100} />
              <h3 className="text-xl font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="text-l py-3">
                creating elegant designs suited for your need following core
                design theory
              </p>
              <h4 className="text-teal-500 py-2 ">Design tools i use </h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Illustrator
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
            </div>
            <div className="shadow-lg p-8 rounded-xl text-center my-10 dark:shadow-cyan-500/50 ">
              <Image src={Consulting} width={100} height={100} />
              <h3 className="text-xl font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="text-l py-3">
                creating elegant designs suited for your need following core
                design theory
              </p>
              <h4 className="text-teal-500 py-2">Design tools i use </h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Illustrator
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
            </div>
            <div className="shadow-lg p-8 rounded-xl text-center my-10 dark:shadow-cyan-500/50 ">
              <Image src={Code} width={100} height={100} />
              <h3 className="text-xl font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="text-l py-3">
                creating elegant designs suited for your need following core
                design theory
              </p>
              <h4 className="text-teal-500 py-2">Design tools i use </h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Illustrator
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h2 className="text-4xl font-medium py-3 dark:text-gray-200">
              Portfolio
            </h2>
            <p className="text-md font-medium text-gray-800 py-1 leading-7 dark:text-gray-200">
              Since the begning of my jounreny as a freelancer designer and
              developer, i have done remote work for{" "}
              <span className="text-teal-500">agencies</span> consulted for{" "}
              <span className="text-teal-500">startups</span> and collaborated
              with talented people to create digital products for both bussiness
              and consumer use.
            </p>
            <p className="text-md font-medium text-gray-800 leading-7 dark:text-gray-200">
              I offer from a wide range of services, including vrand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
